In [6]:
import xgboost as xgb
import numpy as np

In [2]:
model = xgb.Booster()

In [3]:
model.load_model("/workspace/ltr_output/xgb_model.model")

In [4]:
model.best_ntree_limit

5

```
0.5000  qid:259 1:10.4668       2:10.4668       3:3.9000        4:65.0000       5:0.0000        6:0.0000        7:8.3724        8:8.3724        9:0.4506        10:0.0000       11:0.0000       12:4.5004       13:0.0000 # 2070351     1.0     Boxee   fake
```

In [ ]:
model.predict()

In [7]:
data = np.random.rand(5, 10)  # 5 entities, each contains 10 features
label = np.random.randint(2, size=5)  # binary target

In [8]:
data

array([[0.30072317, 0.8668294 , 0.94859278, 0.62038511, 0.52943825,
        0.38424528, 0.31498288, 0.80050944, 0.90695185, 0.10642605],
       [0.02035399, 0.46151455, 0.85182918, 0.06007476, 0.11094623,
        0.62306886, 0.45991521, 0.87570277, 0.87210667, 0.18899814],
       [0.87208086, 0.74252784, 0.26295834, 0.61735449, 0.42915841,
        0.50484411, 0.42262446, 0.89524497, 0.2459917 , 0.37797883],
       [0.79094815, 0.17225675, 0.45875748, 0.19552399, 0.71049662,
        0.5381781 , 0.0570501 , 0.2339552 , 0.19821176, 0.01712589],
       [0.58416951, 0.84063865, 0.40913424, 0.24521498, 0.77034799,
        0.83620859, 0.81963388, 0.86190934, 0.50748383, 0.92947844]])

In [9]:
label

array([0, 1, 0, 0, 0])

In [14]:
data = [[10.4668,10.4668,3.9000,65.0000,0.0000,0.0000,8.3724,8.3724,0.4506,0.0000,0.0000,4.5004,0.0000]]

In [152]:
m = {
  "unknown": 0.0,
  "name_match": 0.0,
  "name_phrase_match": 0.0,
  "customer_review_average_factor": 0.0,
  "customerReviewCount": 0.0,
  "short_description_match": 0.0,
  "artist_name_match": 0.0,
  "long_description_phrase_match": 0.0,
  "long_description_match": 0.0,
  "salesRankShortTerm": 0.0,
  "sku_match": 0.0,
  "manufacturer_match": 0.0,
  "features_match": 0.0,
  "category_path_match": 0.0
}

In [161]:
m = {
  "unknown": 0.0,
  "name_match": 0.0,
  "name_phrase_match": 0.0,
  "customer_review_average_factor": 0.0,
  "customerReviewCount": 100.0,
  "short_description_match": 0.0,
  "artist_name_match": 0.0,
  "long_description_phrase_match": 0.0,
  "long_description_match": 0.0,
  "salesRankShortTerm": 0.0,
  "sku_match": 0.0,
  "manufacturer_match": 0.0,
  "features_match": 0.0,
  "category_path_match": 0.0
}
data = [list(m.values())]
d = xgb.DMatrix(data)
model.predict(d)

array([0.20822585], dtype=float32)

In [171]:
np.array(data).shape

(1, 14)

In [169]:
eli5.show_prediction(model, np.array(data))

ValueError: Please reshape the input data into 2-dimensional matrix.

In [166]:
eli5.explain_prediction_xgboost(model, d.iloc[0])

AttributeError: 'DMatrix' object has no attribute 'iloc'

In [26]:
print(model.feature_importances_)

AttributeError: 'Booster' object has no attribute 'feature_importances_'

In [30]:
vars(model)

{'handle': c_void_p(94898683762560),
 'best_iteration': 4,
 'best_ntree_limit': 5}

In [119]:
!pip install eli5

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.2/216.2 kB 7.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for eli5, since package 'wheel' is not installed.
  Running setup.py install for eli5 ... done


In [120]:
import eli5

In [121]:
eli5.show_weights(model, top=30)

In [ ]:
eli5.